	CREATE DATABASE GIMNASIO

	USE GIMNASIO

	CREATE TABLE MAE_USUARIO
	(
	CODIGO INT IDENTITY,
	CORREO VARCHAR (50),
	CLAVE VARCHAR (20),
	NOMBRE VARCHAR (20),
	TIPO NVARCHAR (20),
	CONSTRAINT UQ_CORREO UNIQUE (CORREO),
	)

	INSERT INTO MAE_USUARIO VALUES ('admin@gmail.com', '123', 'Administrador', 'Admin')
	INSERT INTO MAE_USUARIO VALUES ('pedro@gmail.com', '123', 'Pedro', 'Regular')


	ALTER PROCEDURE CONSULTAR_CUENTA
	@CORREO VARCHAR (50),
	@CLAVE VARCHAR (20)
	AS
	BEGIN
	SELECT CODIGO, CORREO, CLAVE, NOMBRE, TIPO FROM MAE_USUARIO WHERE CORREO = @CORREO AND CLAVE = @CLAVE
	END

	EXEC CONSULTAR_CUENTA 'fernanda@gmail.com', '123'

	CREATE PROCEDURE INSERTAR_USUARIO
	@CORREO VARCHAR (50),
	@CLAVE VARCHAR (20),
	@NOMBRE VARCHAR (20),
	@TIPO NVARCHAR (20)
	AS
	BEGIN 
	INSERT INTO MAE_USUARIO (CORREO, CLAVE, NOMBRE, TIPO) VALUES (@CORREO, @CLAVE, @NOMBRE, @TIPO)
	END


	CREATE PROCEDURE BORRAR_USUARIO
	@CODIGO INT
	AS
	BEGIN
	DELETE
	MAE_USUARIO WHERE CODIGO=@CODIGO
	END


	CREATE PROCEDURE VALIDAR_USUARIO
	@CORREO VARCHAR (50),
	@CLAVE VARCHAR (20)
	AS
	BEGIN
	SELECT CORREO, NOMBRE, CLAVE, TIPO FROM MAE_USUARIO WHERE CORREO=@CORREO AND CLAVE=@CLAVE
	END

	CREATE PROCEDURE BUSCAR_USUARIO
	@CLAVE VARCHAR (20)
	AS
	BEGIN
	SELECT CORREO, NOMBRE, CLAVE, TIPO FROM MAE_USUARIO WHERE CLAVE=@CLAVE
	END

	EXEC BUSCAR_USUARIO '123'
	EXEC VALIDAR_USUARIOA 'admin@gmail.com', '123'




	ALTER PROCEDURE ACTUALIZAR_USUARIO
	@CODIGO INT,
	@CORREO VARCHAR (50),
	@CLAVE VARCHAR (20),
	@NOMBRE VARCHAR (20),
	@TIPO NVARCHAR (20)
	AS
	BEGIN 
	UPDATE MAE_USUARIO SET CORREO=@CORREO, CLAVE=@CLAVE, NOMBRE=@NOMBRE, TIPO=@TIPO
	WHERE CODIGO=@CODIGO
	END


	EXEC CONSULTAR_USUARIO
	EXEC INSERTAR_USUARIO 'fernanda@gmail.com', '123', 'fernanda', 'Admin'
	EXEC INSERTAR_USUARIO 'maryeri@gmail.com', '333', 'maryeri', 'Admin'
	EXEC BORRAR_USUARIO '3'
	EXEC ACTUALIZAR_USUARIO 2, 'pedro@gmail.com', '111', 'Pedro', 'Regular'
	---------------------------------------

	CREATE TABLE CLIENTES
	(
	CODIGO INT IDENTITY,
	NOMBRE VARCHAR (20),
	APELLIDO VARCHAR (20),
	TELEFONO VARCHAR (20),
	CONSTRAINT PK_CODIGO PRIMARY KEY (CODIGO),
	)

	CREATE PROCEDURE INSERTAR_CLIENTE
	@NOMBRE VARCHAR (50),
	@APELLIDO VARCHAR (20),
	@TELEFONO VARCHAR (20)
	AS
	BEGIN 
	INSERT INTO CLIENTES (NOMBRE, APELLIDO, TELEFONO) VALUES (@NOMBRE, @APELLIDO, @TELEFONO)
	END


	ALTER PROCEDURE BORRAR_CLIENTE
	@CODIGO INT
	AS
	BEGIN
	DELETE CLIENTES WHERE CODIGO=@CODIGO
	END


	ALTER PROCEDURE ACTUALIZAR_CLIENTE
	@CODIGO INT,
	@NOMBRE VARCHAR (50),
	@APELLIDO VARCHAR (20),
	@TELEFONO VARCHAR (20)
	AS
	BEGIN 
	UPDATE CLIENTES SET NOMBRE=@NOMBRE, APELLIDO=@APELLIDO, TELEFONO=@TELEFONO
	WHERE CODIGO=@CODIGO
	END

	ALTER PROCEDURE CONSULTAR_CLIENTE
	AS
	BEGIN
	SELECT CODIGO, NOMBRE, APELLIDO, TELEFONO FROM CLIENTES
	END


	EXEC INSERTAR_CLIENTE 'Leana', 'Pereira', '70923796'
	EXEC INSERTAR_CLIENTE 'Manuel', 'Morera', '83649020'
	EXEC BORRAR_CLIENTE '6'
	EXEC ACTUALIZAR_CLIENTE 2, 'Manuel', 'Brito', '83649020'
	EXEC CONSULTAR_CLIENTE


	--------------------------------------------------------------------------------------
	CREATE TABLE DET_FACTURA
	(
	CODIGO INT IDENTITY,
	NFACTURA VARCHAR (50),
	CODIGO_PRODUCTO INT,
	CANTIDAD INT,
	PRECIO_UNITARIO INT,
	IVA INT,
	CONSTRAINT PK_CODIGO_F PRIMARY KEY (CODIGO),
	CONSTRAINT FK_NFACTURA FOREIGN KEY (NFACTURA) REFERENCES MAE_FACTURA (NFACTURA),
	)


	SELECT CODIGO, NOMBRE, APELLIDO, TELEFONO FROM CLIENTES

	CREATE TABLE PRODUCTO
	(
	CODIGO INT IDENTITY,
	NOMBRE VARCHAR (20),
	PRECIO INT,
	CONSTRAINT PK_CODIGO_P PRIMARY KEY (CODIGO),
	)

	CREATE TABLE MAE_FACTURA
	(
	CODIGO INT IDENTITY,
	NFACTURA VARCHAR (50),
	FECHA VARCHAR (20),
	CODIGO_CLIENTE INT,
	TOTAL INT,
	IV_TOTAL INT,
	CONSTRAINT PK_NFACTURA PRIMARY KEY (NFACTURA),
	CONSTRAINT FK_CODIGO_CLIENTE FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTES (CODIGO),
	)

	INSERT INTO MAE_FACTURA VALUES('1234','18-12-2022', '1002', '35000', '3000')

	CREATE PROCEDURE SELECCIONAR_PRODUCTO
	@CODIGO INT
	AS 
	BEGIN 
	SELECT CODIGO, NOMBRE, PRECIO FROM PRODUCTO WHERE CODIGO = @CODIGO
	END

	CREATE PROCEDURE SELECCIONAR_FACTURAS
	AS 
	BEGIN 
	SELECT CODIGO, NFACTURA, FECHA, CODIGO_CLIENTE, TOTAL, IV_TOTAL FROM MAE_FACTURA
	END

	CREATE PROCEDURE MAE_FACTURAA
	@CODIGO_CLIENTE INT,
	@TOTAL INT,
	@FECHA VARCHAR(20)
	AS 
	BEGIN
	INSERT INTO MAE_FACTURA (FECHA,CODIGO_CLIENTE ,TOTAL) VALUES (@FECHA,@CODIGO_CLIENTE,@TOTAL)
	END



	CREATE PROCEDURE DETALLE_FACTURA
	@NFACTURA INT,
	@CODIGO_PRODUCTO INT,
	@CANTIDAD INT,
	@PRECIO_UNITARIO INT
	AS
	BEGIN
	DECLARE @CODIGO INT
	SET @CODIGO = (SELECT TOP 1 CODIGO FROM MAE_FACTURA ORDER BY CODIGO DESC)
	INSERT INTO DET_FACTURA (CODIGO,NFACTURA,CODIGO_PRODUCTO,CANTIDAD,PRECIO_UNITARIO) VALUES (@CODIGO,@NFACTURA,@CODIGO_PRODUCTO,@CANTIDAD,@PRECIO_UNITARIO)
	END

	EXEC SELECCIONAR_PRODUCTO  2
	EXEC MAE_FACTURA 'MIGUEL',2300
	EXEC MAE_FACTURA  1, 6000
 

	------------------------------------------

	CREATE TABLE PROVINCIA
	(
	CODIGO INT IDENTITY,
	NOMBRE VARCHAR (20),
	CONSTRAINT PK_CODIGO_PR PRIMARY KEY (CODIGO),
	)

	CREATE TABLE CANTON
	(
	CODIGO INT IDENTITY,
	NOMBRE VARCHAR (20),
	CODIGO_PROVINCIA INT,
	CONSTRAINT PK_CODIGO_C PRIMARY KEY (CODIGO),
	CONSTRAINT FK_CODIGO FOREIGN KEY (CODIGO_PROVINCIA) REFERENCES PROVINCIA (CODIGO),
	)

	CREATE TABLE DISTRITO
	(
	CODIGO INT IDENTITY,
	NOMBRE VARCHAR (20),
	CODIGO_CANTON INT,
	CONSTRAINT PK_CODIGO_D PRIMARY KEY (CODIGO),
	CONSTRAINT FK_CODIGO_C FOREIGN KEY (CODIGO_CANTON) REFERENCES CANTON (CODIGO),
	)


	CREATE TABLE DIRECCIONES
	(
	CODIGO INT IDENTITY,
	CODIGO_CLIENTE INT,
	CODIGO_PROVINCIA INT,
	CODIGO_CANTON INT,
	CODIGO_DISTRITO INT,
	COMENTARIOS VARCHAR (200),
	CONSTRAINT PK_CODIGODIR PRIMARY KEY (CODIGO),
	CONSTRAINT FK_CODIGOCLIENTE FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTES (CODIGO),
	CONSTRAINT FK_CODIGOPROVINCIA FOREIGN KEY (CODIGO_PROVINCIA) REFERENCES PROVINCIA (CODIGO),
	CONSTRAINT FK_CODIGOCANTON FOREIGN KEY (CODIGO_CANTON) REFERENCES CANTON (CODIGO),
	CONSTRAINT FK_CODIGODISTRITO FOREIGN KEY (CODIGO_DISTRITO) REFERENCES DISTRITO (CODIGO),
	)

